# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      dir
    workingDirectory: '$(system.defaultworkingdirectory)'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo %cd%
    npm install
  displayName: 'npm install'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo %cd%
    dir
    npm run build --prod
  displayName: 'npm build'
  
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      dir
    workingDirectory: '$(system.defaultworkingdirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dist/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(build.artifactstagingdirectory)
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      dir
    workingDirectory: '$(build.artifactstagingdirectory)'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(build.artifactstagingdirectory)'
    azureSubscription: 'ResourceShare-connection'
    Destination: 'AzureBlob'
    storage: 'cataylst'
    ContainerName: '$web'
